export const globalContent = {
  brand: 'Dispute Levels',
  phone: '754-704-4737',
  email: 'support@disputelevelcreditrestoration.com',
  billingUrl: 'https://kbrownconsultantgroupllc.getcredithelpnow.com/billing',
  clientPortalUrl: 'https://www.secureclientaccess.com/',
  creditRepairCloudScript: 'https://app.creditrepaircloud.com/app/widget.umd.cjs',
  signupLabel: 'Sign Up For $0 Today',
  navigation: [
    { label: 'Home', to: '/' },
    { label: 'About Us', to: '/about' },
    { label: 'Pricing', to: '/pricing' },
    { label: 'Our Services', to: '/services' },
    { label: 'Partners', to: '/partners' },
    { label: 'Tradelines', to: '/tradelines' },
  ],
  companyLinks: [
    { label: 'About us', to: '/about' },
    { label: 'Pricing', to: '/pricing' },
    { label: 'Success stories', to: '/success-stories' },
    { label: 'Our Services', to: '/services' },
  ],
  supportLinks: [
    { label: 'Credit info', to: '/credit-info' },
    { label: 'FAQ', to: '/faq' },
    { label: 'Contact us', to: '/contact' },
  ],
  legalLinks: [
    { label: 'Privacy Policy', to: '/privacy' },
    { label: 'Terms of Service', to: '/terms' },
    { label: 'Refund Policy', missing: true },
    { label: 'Consumer Rights Notice', missing: true },
    { label: 'Contact Us', to: '/contact' },
    { label: 'Accessibility Statement', missing: true },
  ],
  disclosureTitle: 'Important Disclosure',
  disclosure: 'We provide credit education, consultation, and administrative support services. We do not guarantee the removal of accurate information from credit reports, specific credit score increases, financing approvals, or other outcomes. Results vary based on individual circumstances.',
  consumerRights: 'You have the right to dispute inaccurate information directly with credit reporting agencies at no cost.',
  description: 'Credit education, consultation, and administrative support to help consumers better understand their credit reports.',
  copyright: '© 2026 Dispute Levels. All rights reserved.',
};
