export const homepageContent = {
  hero: {
    eyebrow: 'Education-Driven Approach',
    title: 'Improve Your Credit Profile With Personalized Guidance',
    copy: 'Our team helps consumers understand their credit reports, identify potential reporting issues, and take informed steps toward building stronger credit habits and financial confidence.',
    benefits: ['Personalized Credit Review', 'Credit Education', 'Customized Action Plan'],
    primaryCta: { label: 'Schedule a consultation', to: '#consultation' },
    secondaryCta: { label: 'View Pricing Plans', to: '#pricing' },
    disclaimer: 'Results vary based on individual circumstances. We do not guarantee specific credit score increases, loan approvals, or the removal of accurate information from credit reports.',
    backgroundVideo: '/assets/7821647-hd_1920_1080_30fps.mp4',
    image: '/assets/kevin-with-laptop.png',
    imageAlt: 'Happy family reviewing finances',
    proof: [
      { label: 'Review', title: 'Credit Review', detail: 'Personalized summary' },
      { label: 'Action Plan', title: 'Next steps' },
    ],
  },
  trustItems: [
    'Helping Consumers Navigate Credit Challenges',
    'Thousands of Client Consultations Conducted',
    'Personalized Credit Action Plans',
    'Ongoing Support Throughout The Process',
    'Education-Driven Approach',
  ],
  benefits: {
    eyebrow: 'Benefits',
    title: "What You'll Receive",
    items: [
      { title: 'Personalized Credit Review', copy: 'We review your credit reports and discuss areas that may be impacting your credit profile.' },
      { title: 'Credit Education', copy: 'Learn how payment history, utilization, collections, inquiries, and other factors can affect your credit standing.' },
      { title: 'Customized Action Plan', copy: 'Receive recommendations tailored to your unique financial situation and goals.' },
    ],
  },
  process: {
    eyebrow: 'Process',
    title: 'How Our Process Works',
    copy: 'A simple, guided process designed to help you understand your credit profile and take informed steps forward.',
    items: [
      { number: '1', title: 'Schedule Your Consultation', copy: 'Meet with a credit specialist to discuss your goals and review your current credit situation.' },
      { number: '2', title: 'Review & Strategy', copy: 'We help identify potential reporting concerns and create a personalized action plan.' },
      { number: '3', title: 'Ongoing Support', copy: 'Receive guidance and support as you work toward improving your credit profile over time.' },
    ],
    disclaimer: 'Credit reporting investigations and outcomes depend on responses from credit bureaus, creditors, and other third parties.',
  },
  pricing: {
    eyebrow: 'PRICING',
    title: "Choose The Level Of Support That's Right For You",
    copy: 'Select the plan that fits your situation and get started today.',
    plans: [
      {
        tier: 'Individual',
        name: 'OPTIMIZATION TIER1',
        firstPayment: '$359',
        firstPaymentLabel: 'First Payment',
        recurring: '$225',
        recurringLabel: '/ month',
        paymentCopy: 'Charged every 30 days as long as your membership is active.',
        features: ['Credit report review', 'Personalized action plan', 'Educational resources', 'Initial consultation'],
        cta: 'Get Started',
        href: 'https://kbrownconsultantgroupllc.getcredithelpnow.com/checkout-OPTIMIZATIONTIER1',
      },
      {
        badge: 'Most Popular',
        tier: 'Group',
        name: 'CREDIT OPTIMIZATION PLAN GROUP',
        firstPayment: '$799',
        firstPaymentLabel: 'First Payment',
        recurring: '$399',
        recurringLabel: '/ month',
        paymentCopy: 'Charged every 30 days as long as your membership is active.',
        features: ['Support for group', 'Credit reviews', 'Action plans', 'Ongoing educational resources'],
        cta: 'Get Started',
        href: 'https://kbrownconsultantgroupllc.getcredithelpnow.com/checkout-CREDITOPTIMIZATIONPLANGROUP',
      },
      {
        tier: 'Premier',
        name: 'Homebuyer Path Premier Promo',
        firstPayment: '$2250',
        firstPaymentLabel: 'Only charged once',
        paymentCopy: 'Credit Repair Services Payment.',
        features: ['Comprehensive credit report review', 'Advanced action plan', 'Premium educational resources', 'Priority support'],
        cta: 'Get Started',
        href: 'https://kbrownconsultantgroupllc.getcredithelpnow.com/checkout-HomebuyerPathPremierPromo',
      },
    ],
    disclaimer: 'Fees are charged for services rendered and do not guarantee any specific outcome, score increase, account removal, or lending approval.',
  },
  utilization: {
    eyebrow: 'Premium Tradelines',
    title: 'Boost Your Credit Profile with Authorized User Tradelines',
    copy: 'Adding an aged, high-limit credit card to your credit report as an authorized user can significantly lower your credit utilization ratio and increase your average age of accounts. We offer a curated list of premium tradelines from major banks to help you achieve your financial goals faster.',
    points: ['Increase Credit Limits', 'Lower Credit Utilization', 'Increase Average Account Age'],
    cta: { label: 'View Available Tradelines', to: '/tradelines' },
    card: { label: 'PREMIUM CARD', limitLabel: 'Credit Limit', limit: '$26,800', openedLabel: 'Opened', opened: '03 / 20', status: 'Perfect History' },
  },
  services: {
    eyebrow: 'SERVICES',
    title: 'Services Designed To Support Your Credit Goals',
    copy: 'Educational support and guidance to help you better understand your credit profile and options.',
    items: [
      { title: 'Credit Report Review', copy: 'Detailed review of information appearing on your credit reports.' },
      { title: 'Dispute Assistance', copy: 'Assistance with identifying potentially inaccurate, incomplete, or unverifiable information for review.' },
      { title: 'Credit Education', copy: 'Learn the factors that influence credit scores and long-term credit health.' },
      { title: 'Collection Account Guidance', copy: 'Understand available options when dealing with collection accounts.' },
      { title: 'Credit Utilization Coaching', copy: 'Learn strategies that may help improve credit utilization management.' },
      { title: 'Ongoing Monitoring Support', copy: 'Stay informed about changes to your credit profile and reporting activity.' },
    ],
    cta: { label: 'See All Services', to: '/services' },
  },
  audience: {
    eyebrow: 'WHO WE HELP',
    title: 'Supporting Consumers From Many Walks Of Life',
    copy: 'Educational guidance and support for a wide range of credit goals and milestones.',
    items: [
      { title: 'Individuals Building Credit', copy: "Whether you're establishing credit or rebuilding after setbacks, we provide educational support and guidance." },
      { title: 'Families', copy: 'Helping households better understand credit and financial management.' },
      { title: 'Small Business Owners', copy: 'Guidance for business owners seeking to strengthen personal credit profiles.' },
      { title: 'Professionals', copy: 'Support for consumers preparing for major financial milestones.' },
    ],
  },
  whyChoose: {
    eyebrow: 'WHY CLIENTS CHOOSE US',
    title: 'Why Clients Work With Our Team',
    copy: 'Clear guidance, education-first support, and transparent communication throughout the process.',
    items: [
      { title: 'Personalized Service', copy: 'Every client receives an individualized review and action plan.' },
      { title: 'Education First', copy: 'We focus on helping clients understand their credit profile and available options.' },
      { title: 'Transparent Communication', copy: 'Clear expectations and ongoing updates throughout the process.' },
      { title: 'Compliance-Focused Approach', copy: 'We operate with transparency and consumer protection principles in mind.' },
    ],
  },
  video: {
    title: 'Hear From Our Clients',
    copy: 'Our clients share their personal experiences working with our team.',
    src: 'https://assets.cdn.filesafe.space/RUJav8DkqzOZYSDowGV8/media/69b0e39c03488615e50be676.mov',
    disclaimer: 'Testimonials reflect individual experiences. Results vary and are not guaranteed.',
    cta: { label: 'View Pricing Plans', href: 'https://kbrownconsultantgroupllc.getcredithelpnow.com/billing' },
  },
  testimonials: {
    eyebrow: 'Client Experiences',
    title: 'Client Experiences',
    disclaimer: 'These testimonials reflect individual experiences. Individual outcomes vary and may not represent the typical client experience.',
    items: [
      { quote: '"The team helped me better understand my credit report and gave me a clear plan to move forward."', name: 'Client', detail: 'Credit Review' },
      { quote: '"I appreciated the education and guidance throughout the process."', name: 'Client', detail: 'Education' },
      { quote: '"The consultation helped me identify areas I could improve."', name: 'Client', detail: 'Consultation' },
    ],
  },
  rights: {
    title: 'Know Your Rights',
    intro: 'Consumers have important rights under federal law.',
    copy: 'You may take action directly with credit reporting agencies and creditors. Our services are optional and results vary.',
    listTitle: 'You Have The Right To:',
    items: [
      'Obtain copies of your credit reports',
      'Dispute inaccurate information directly with credit bureaus',
      'Receive investigation results from credit reporting agencies',
      'Cancel certain agreements within applicable cancellation periods',
    ],
    noticeTitle: 'Consumer Notice',
    notice: 'You may dispute inaccurate information directly with the credit bureaus at no cost. Purchasing our services is not required to exercise your legal rights.',
  },
  consultation: {
    title: 'Schedule Your Credit Consultation',
    intro: 'Speak with a member of our team to review your situation and discuss available options.',
    copy: 'Get a no-obligation consultation with educational guidance and a personalized review.',
    cta: { label: 'Book Your Consultation', to: '#consultation-calendar' },
    points: ['No obligation consultation', 'Personalized review', 'Educational guidance', 'Questions answered by our team'],
    bookingUrl: 'https://link.kbcnsult.com/widget/booking/2FdegAiF26T5ryjb1wRs',
  },
  finalCta: {
    title: 'Take The First Step Toward A Stronger Credit Profile',
    copy: 'Learn more about your credit report, understand your options, and create a personalized plan for moving forward.',
    primary: { label: 'Schedule Consultation', to: '#consultation' },
    secondary: { label: 'Get Started Today For $0', href: 'https://kbrownconsultantgroupllc.getcredithelpnow.com/billing' },
    disclaimer: 'Results vary. We do not guarantee specific credit score increases, credit report changes, financing approvals, or other outcomes.',
  },
};
